use ../lib/prelude.nu *
use bootstrap.nu [bootstrap-brew-items]

# Environment variables applied to every Homebrew invocation, from the
# software.homebrew.env configuration. This is how a private state routes
# brew itself, taps, and bottles through a mirror (e.g. a China mirror).
export def homebrew-env [
  settings: record # Homebrew manager settings.
]: nothing -> record {
  $settings.env? | default {}
}

# Escape an environment value into a literal for one of the four snippet
# syntaxes. POSIX shells cannot escape a single quote inside a single-quoted
# string at all, so it uses the '\'' splice; Fish backslash-escapes quotes,
# PowerShell doubles them, and Nushell uses a double-quoted string with
# backslash escapes.
def quote-env-value [
  value: string # Environment value to quote.
  syntax: string # "nu", "fish", "posix", or "powershell".
]: nothing -> string {
  if $syntax == "nu" {
    let escaped = ($value | str replace --all "\\" "\\\\" | str replace --all "\"" "\\\"")
    $"\"($escaped)\""
  } else if $syntax == "posix" {
    $value | str replace --all "'" "'\\''"
  } else if $syntax == "fish" {
    $value | str replace --all "\\" "\\\\" | str replace --all "'" "\\'"
  } else {
    $value | str replace --all "'" "''"
  }
}

# Friendly label for the mirror configured through software.homebrew.env, or
# "" when no mirror environment is set. Recognizes the USTC and TUNA mirror
# hosts; any other configured domain is reported as a custom mirror.
export def homebrew-mirror-label [
  environment: record # Homebrew environment from the settings.
]: nothing -> string {
  let domains = ([HOMEBREW_BOTTLE_DOMAIN HOMEBREW_API_DOMAIN HOMEBREW_BREW_GIT_REMOTE HOMEBREW_CORE_GIT_REMOTE HOMEBREW_CASK_GIT_REMOTE]
    | each {|key| $environment | get -o $key | default "" }
    | where {|value| not ($value | is-empty) }
    | uniq)
  if ($domains | is-empty) {
    ""
  } else if ($domains | any {|value| $value | str contains "mirrors.ustc.edu.cn" }) {
    "ustc (mirrors.ustc.edu.cn)"
  } else if ($domains | any {|value| $value | str contains "mirrors.tuna.tsinghua.edu.cn" }) {
    "tuna (mirrors.tuna.tsinghua.edu.cn)"
  } else {
    $"custom \((($domains | first))\)"
  }
}

# The four persistent snippet destinations, shared by generation and
# stale-removal so the paths cannot drift.
def homebrew-env-snippet-paths []: nothing -> list<path> {
  let xdg_config_home = if not (($env.XDG_CONFIG_HOME? | default "" | str trim) | is-empty) {
    $env.XDG_CONFIG_HOME | path expand --no-symlink
  } else {
    $nu.home-dir | path join ".config"
  }
  [
    ($nu.data-dir | path join "vendor" "autoload" "reseed-homebrew-env.nu")
    ($xdg_config_home | path join "fish" "conf.d" "reseed-homebrew-env.fish")
    ($nu.home-dir | path join ".local" "share" "reseed" "shell" "reseed-homebrew-env.sh")
    ($nu.home-dir | path join ".local" "share" "reseed" "shell" "reseed-homebrew-env.ps1")
  ]
}

# Shell snippet files that export the configured Homebrew environment so
# interactive brew usage outside Reseed also uses the mirror. The Nushell
# vendor autoload and Fish conf.d snippets load automatically; the POSIX and
# PowerShell files live in the managed shell directory to source from a
# profile. Empty when no environment is configured.
export def homebrew-shell-snippets [
  config: record # Loaded configuration.
]: nothing -> list<record> {
  let environment = (homebrew-env ($config.software.homebrew? | default {}))
  if ($environment | is-empty) { return [] }
  let home = $nu.home-dir
  let managed_shell = ($home | path join ".local" "share" "reseed" "shell")
  let pairs = ($environment | transpose key value | sort-by key)
  let nu_lines = ($pairs | each {|entry| let quoted = (quote-env-value $entry.value "nu"); $"$env.($entry.key) = ($quoted)" })
  let fish_lines = ($pairs | each {|entry| let quoted = (quote-env-value $entry.value "fish"); $"set -gx ($entry.key) '($quoted)'" })
  let posix_lines = ($pairs | each {|entry| let quoted = (quote-env-value $entry.value "posix"); $"export ($entry.key)='($quoted)'" })
  let powershell_lines = ($pairs | each {|entry| let quoted = (quote-env-value $entry.value "powershell"); $"$env:($entry.key) = '($quoted)'" })
  [
    {
      path: (homebrew-env-snippet-paths | get 0)
      lines: (["# Generated by Reseed; changes are overwritten by the next restore."] | append $nu_lines)
    }
    {
      path: (homebrew-env-snippet-paths | get 1)
      lines: (["# Generated by Reseed; changes are overwritten by the next restore."] | append $fish_lines)
    }
    {
      path: (homebrew-env-snippet-paths | get 2)
      lines: (["# Generated by Reseed; source this file from bash, zsh, or another POSIX profile."] | append $posix_lines)
    }
    {
      path: (homebrew-env-snippet-paths | get 3)
      lines: (["# Generated by Reseed; dot-source this file from the current user's PowerShell profile."] | append $powershell_lines)
    }
  ]
}

# Remove any existing Homebrew env snippets for the current user.
def remove-homebrew-snippets [
  --dry-run # Report the removals without deleting files.
] {
  for path in (homebrew-env-snippet-paths) {
    if ($path | path exists) {
      if $dry_run {
        info $"would remove stale Homebrew env snippet: ($path)"
      } else {
        rm $path
        info $"removed stale Homebrew env snippet: ($path)"
      }
    }
  }
}

# Write the persistent Homebrew mirror snippets for the current user, or
# remove stale ones when the environment is emptied or Homebrew is disabled.
# Runs on every platform, matching the shell adapters of the reseed:shells
# task; without a configured environment the snippets are simply removed.
export def homebrew-persist-env [
  config: record # Loaded configuration.
  --dry-run # Report the writes without changing files.
] {
  let settings = ($config.software.homebrew? | default {})
  if not ($settings.enabled? | default false) {
    remove-homebrew-snippets --dry-run=$dry_run
    return
  }
  let snippets = (homebrew-shell-snippets $config)
  if ($snippets | is-empty) {
    remove-homebrew-snippets --dry-run=$dry_run
    return
  }
  for snippet in $snippets {
    if $dry_run {
      info $"would write Homebrew env snippet: ($snippet.path)"
    } else {
      mkdir ($snippet.path | path dirname)
      (($snippet.lines | str join "\n") + "\n") | save --force $snippet.path
      info $"wrote Homebrew env snippet: ($snippet.path)"
    }
  }
}

# Declared entries of a Brewfile (brew/cask/tap/mas/vscode lines), with
# trailing comments stripped.
export def brewfile-items [
  path: path # Brewfile path.
]: nothing -> list<string> {
  if not ($path | path exists) { return [] }
  open --raw $path
    | lines
    | each {|line| $line | str trim }
    | where {|line| ($line =~ '^(brew|cask|tap|mas|vscode)\s+"') }
    | each {|line| $line | str replace --regex '\s*#.*$' '' }
    | uniq
    | sort
}

# Brewfile entries excluding the bootstrap-contract tools the engine installs
# itself.
export def native-brewfile-items [
  path: path # Brewfile path.
]: nothing -> list<string> {
  brewfile-items $path | where {|item| $item not-in (bootstrap-brew-items) }
}

# Short summary of a Brewfile's declared entries, e.g. "2 formulas, 1 cask".
export def brewfile-summary [
  path: path # Brewfile path.
]: nothing -> string {
  let items = (brewfile-items $path)
  if ($items | is-empty) { return "0 entries" }
  let kinds = [
    {prefix: brew label: formula plural: formulas}
    {prefix: cask label: cask plural: casks}
    {prefix: tap label: tap plural: taps}
    {prefix: mas label: app plural: apps}
    {prefix: vscode label: extension plural: extensions}
  ]
  let parts = ($kinds | each {|kind|
    let count = ($items | where {|item| $item | str starts-with $"($kind.prefix) \"" } | length)
    if $count > 0 { $"($count) (if $count == 1 { $kind.label } else { $kind.plural })" } else { null }
  } | compact)
  if ($parts | is-empty) { "0 entries" } else { $parts | str join ", " }
}

# Availability and desired-manifest health for the Homebrew integration.
export def homebrew-status [
  root: path # Private state root.
  config: record # Loaded configuration.
]: nothing -> record {
  let settings = $config.software.homebrew
  let manifests = ($settings.manifests? | default [])
  {
    tool: homebrew
    enabled: ($settings.enabled? | default false)
    applicable: ((detect-os) == "macos")
    available: (command-exists brew)
    desired: ($manifests | each {|item| {path: $item exists: (($root | path join $item) | path exists)} })
  }
}

# Echo the active Homebrew mirror and the environment variables that route
# brew through it. Prints nothing when no mirror environment is configured.
def show-homebrew-mirror [
  environment: record # Homebrew environment from the settings.
] {
  let mirror = (homebrew-mirror-label $environment)
  if ($mirror | is-empty) { return }
  info $"Homebrew mirror: ($mirror)"
  for entry in ($environment | transpose key value | where {|entry| $entry.key | str starts-with "HOMEBREW_" } | sort-by key) {
    info $"  ($entry.key)=($entry.value)"
  }
}

# Install every configured Brewfile.
export def homebrew-restore [
  root: path # Private state root.
  config: record # Loaded configuration.
  --dry-run # Show the installs without running them.
] {
  let settings = $config.software.homebrew
  if not ($settings.enabled? | default false) or ((detect-os) != "macos") { return }
  if not (command-exists brew) and not $dry_run { error make {msg: "Homebrew is required for the macOS package stage"} }
  let environment = (homebrew-env $settings)
  show-homebrew-mirror $environment
  for manifest in ($settings.manifests? | default []) {
    let path = ($root | path join $manifest)
    info $"installing Homebrew packages from ($manifest) ((brewfile-summary $path))"
    run-command brew ["bundle" "install" "--verbose" $"--file=($path)"] --environment=$environment --dry-run=$dry_run | ignore
  }
}

# Update Homebrew and upgrade only the packages each Brewfile declares,
# excluding the bootstrap-contract tools.
export def homebrew-update [
  root: path # Private state root.
  config: record # Loaded configuration.
  --dry-run # Show the updates without running them.
] {
  let settings = $config.software.homebrew
  if not ($settings.enabled? | default false) or not ($settings.update? | default true) or ((detect-os) != "macos") { return }
  if not (command-exists brew) { warning "Homebrew is unavailable; skipping macOS package updates"; return }
  let environment = (homebrew-env $settings)
  show-homebrew-mirror $environment
  run-command brew ["update"] --environment=$environment --dry-run=$dry_run | ignore
  for manifest in ($settings.manifests? | default []) {
    let path = ($root | path join $manifest)
    info $"installing Homebrew packages from ($manifest) ((brewfile-summary $path))"
    run-command brew ["bundle" "install" "--verbose" $"--file=($path)"] --environment=$environment --dry-run=$dry_run | ignore
    for kind in [brews casks] {
      upgrade-brewfile-kind $path $kind $environment --dry-run=$dry_run
    }
  }
}

# Parse "brew outdated" output for the requested packages into their names,
# accepting both brew formats ("name installed < available" and
# "name (installed: x) != y"). Exported for tests.
export def parse-outdated-names [
  text: string # Raw "brew outdated" output.
  names: list<string> # Package names to report.
]: nothing -> list<string> {
  $text
    | lines
    | each {|line| $line | str trim | split row " " | get -o 0 | default "" }
    | where {|name| ($name | is-not-empty) and ($name in $names) }
    | uniq
}

# Packages among the given names that brew reports as outdated. Empty when
# the check cannot run or nothing is outdated.
def brew-outdated-names [
  environment: record # Homebrew environment from the settings.
  kind: string # "brews" or "casks".
  names: list<string> # Package names to check.
]: nothing -> list<string> {
  let flag = if $kind == "casks" { "--cask" } else { "--formula" }
  let result = (run-command brew (["outdated" $flag] | append $names) --allow-failure --environment=$environment --capture)
  if $result.exit_code == 127 { [] } else { parse-outdated-names $result.stdout $names }
}

# Upgrade one kind of package (brews or casks) declared in a Brewfile,
# skipping anything the bootstrap contract owns. Only packages brew reports
# as outdated are upgraded, so the summary counts are accurate.
def upgrade-brewfile-kind [
  path: path # Brewfile path.
  kind: string # "brews" or "casks".
  environment: record # Homebrew environment from the settings.
  --dry-run # Show the upgrades without running them.
] {
  let listed = (run-command brew ["bundle" "list" $"--file=($path)" $"--($kind)"] --allow-failure --environment=$environment --dry-run=$dry_run --capture)
  if ($listed.exit_code != 0) or $dry_run { return }
  let names = ($listed.stdout | lines | each {|line| $line | str trim } | compact)
  let ignored_names = (bootstrap-brew-items
    | parse --regex '^(?:brew|cask)\s+"(?<name>[^"]+)"'
    | get -o name
    | default [])
  let names = ($names | where {|name| $name not-in $ignored_names })
  if ($names | is-not-empty) {
    let outdated = (brew-outdated-names $environment $kind $names)
    if ($outdated | is-empty) { return }
    let args = if $kind == "casks" { ["upgrade" "--cask"] | append $outdated } else { ["upgrade"] | append $outdated }
    info $"upgrading ($outdated | length) ($kind)"
    let upgraded = (run-command brew $args --allow-failure --environment=$environment)
    if $upgraded.exit_code != 0 {
      let stderr = ($upgraded.stderr | str trim)
      warning (if ($stderr | is-empty) { $"Some Homebrew ($kind) updates failed" } else { $"Some Homebrew ($kind) updates failed: ($stderr)" })
    } else {
      info $"upgraded ($outdated | length) ($kind)"
    }
  }
}

# True when a Brewfile line is one of the bootstrap-contract entries.
def bootstrap-brew-line? [
  line: string # Brewfile line.
]: nothing -> bool {
  let normalized = ($line | str replace --regex '\s*#.*$' '' | str trim)
  $normalized in (bootstrap-brew-items)
}

# Remove the bootstrap-contract entries from a Brewfile in place.
def filter-bootstrap-brew-items [
  path: path # Brewfile path to rewrite.
] {
  let lines = (open --raw $path | lines | where {|line| not (bootstrap-brew-line? $line) })
  ($lines | str join "\n") | save --force $path
}

# Export the installed formulas and casks to a Brewfile, optionally filtering
# out the bootstrap tools. Export failures degrade to a warning.
def export-brewfile [
  path: path # Destination Brewfile path.
  environment: record # Homebrew environment from the settings.
  --exclude-bootstrap # Filter engine-owned entries from the export.
  --dry-run # Show the export without running it.
]: nothing -> bool {
  if $dry_run {
    run-command brew ["bundle" "dump" $"--file=($path)" "--force"] --environment=$environment --dry-run | ignore
    return true
  }
  mkdir ($path | path dirname)
  let result = (run-command brew ["bundle" "dump" $"--file=($path)" "--force"] --environment=$environment --allow-failure --capture)
  if $result.exit_code != 0 {
    warning $"Brewfile export failed: ($result.stderr | str trim)"
    false
  } else {
    if $exclude_bootstrap { filter-bootstrap-brew-items $path }
    true
  }
}

# Capture the Homebrew inventory. With --refresh-manifests the single
# configured Brewfile is replaced by the live dump; otherwise the dump is
# written as an observation under the disposable state directory.
export def homebrew-backup [
  root: path # Private state root.
  config: record # Loaded configuration.
  --refresh-manifests # Replace the curated Brewfile with the live dump.
  --dry-run # Show the dump without running it.
] {
  let settings = $config.software.homebrew
  if not ($settings.enabled? | default false) or ((detect-os) != "macos") or not (command-exists brew) { return }
  let refresh = $refresh_manifests or ($settings.export_on_backup? | default false)
  let target = if $refresh and (($settings.manifests? | default [] | length) == 1) {
    $root | path join ($settings.manifests | first)
  } else {
    if $refresh { warning "Homebrew refresh requires exactly one target Brewfile; writing an observation instead" }
    observation-dir $config | path join "Brewfile"
  }
  export-brewfile $target (homebrew-env $settings) --exclude-bootstrap=$refresh --dry-run=$dry_run | ignore
  if not $refresh { info $"Homebrew observation: ($target)" }
}

# Compare the curated Brewfiles with a fresh dump, report-only.
export def homebrew-reconcile [
  root: path # Private state root.
  config: record # Loaded configuration.
  --dry-run # Skip the live dump.
]: nothing -> record {
  let settings = $config.software.homebrew
  if not ($settings.enabled? | default false) or ((detect-os) != "macos") {
    return {tool: homebrew applicable: false desired_only: [] observed_only: []}
  }
  if not (command-exists brew) {
    return {tool: homebrew applicable: true error: "brew is unavailable" desired_only: [] observed_only: []}
  }
  let observed = (observation-dir $config | path join "Brewfile")
  if not (export-brewfile $observed (homebrew-env $settings) --dry-run=$dry_run) or $dry_run {
    return {tool: homebrew applicable: true observation: $observed desired_only: [] observed_only: []}
  }
  let desired = ($settings.manifests? | default [] | each {|manifest| native-brewfile-items ($root | path join $manifest) } | flatten | uniq | sort)
  let current = (native-brewfile-items $observed)
  {
    tool: homebrew
    applicable: true
    observation: $observed
    desired_only: ($desired | where {|item| $item not-in $current })
    observed_only: ($current | where {|item| $item not-in $desired })
  }
}

# Verification checks for Homebrew: executable presence, Brewfile health, and
# that every declared package is installed.
export def homebrew-verify [
  root: path # Private state root.
  config: record # Loaded configuration.
]: nothing -> list<record> {
  let settings = $config.software.homebrew
  if not ($settings.enabled? | default false) or ((detect-os) != "macos") { return [] }
  mut results = [{check: "homebrew executable" ok: (command-exists brew) detail: "required on macOS"}]
  for manifest in ($settings.manifests? | default []) {
    let path = ($root | path join $manifest)
    $results = ($results | append {check: $"Brewfile: ($manifest)" ok: ($path | path exists) detail: $"((brewfile-items $path | length)) entries"})
    if (command-exists brew) and ($path | path exists) {
      let checked = (try {
        run-command brew ["bundle" "check" $"--file=($path)"] --environment=(homebrew-env $settings) --allow-failure --capture
      } catch {|error| {exit_code: 1 stdout: "" stderr: ($error.msg? | default "failed to start brew")} })
      $results = ($results | append {
        check: $"Homebrew packages installed: ($manifest)"
        ok: ($checked.exit_code == 0)
        detail: (if $checked.exit_code == 0 { "complete" } else { ($checked.stdout + $checked.stderr | str trim) })
      })
    }
  }
  $results
}
