#!/usr/bin/env nu

# Write lines to a file, creating the parent directory first.
def save-lines [
  path: path # Destination file.
  lines: list<string> # Lines to write, each terminated by a newline.
] {
  mkdir ($path | path dirname)
  (($lines | str join "\n") + "\n") | save --force $path
}

# Install the Starship Nushell init into the vendor autoload directory.
def install-starship-nushell [
  nu_autoload_dir: path # Nushell vendor autoload directory.
  starship_init: path # Destination for "starship init nu" output.
] {
  mkdir $nu_autoload_dir
  run-external starship "init" "nu" | save --force $starship_init
}

# Write the Nushell autoload snippet that points the package managers at the
# managed bin directory and prepends it to PATH.
def write-managed-tools-nu [
  path: path # Destination file.
  managed_bin_literal: string # Managed bin path as a NUON string literal.
  managed_root_literal: string # Managed root path as a NUON string literal.
] {
  save-lines $path [
    "# Generated by Reseed; changes are overwritten by the next restore."
    (('$env.PNPM_HOME = ' + $managed_bin_literal))
    (('$env.UV_TOOL_BIN_DIR = ' + $managed_bin_literal))
    (('$env.YARN_PREFIX = ' + $managed_root_literal))
    (('$env.BUN_INSTALL = ' + $managed_root_literal))
    # prepend + uniq deduplicates the managed bin directory in PATH.
    "$env.PATH = ($env.PATH | prepend $env.PNPM_HOME | uniq)"
  ]
}

# Write the Fish conf.d adapter with the same environment variables.
def write-fish-adapter [
  path: path # Destination file.
] {
  save-lines $path [
    "# Generated by Reseed; changes are overwritten by the next restore."
    'set -gx PNPM_HOME "$HOME/.local/share/reseed/bin"'
    'set -gx UV_TOOL_BIN_DIR "$HOME/.local/share/reseed/bin"'
    'set -gx YARN_PREFIX "$HOME/.local/share/reseed"'
    'set -gx BUN_INSTALL "$YARN_PREFIX"'
    'fish_add_path --move --path "$PNPM_HOME"'
  ]
}

# Write the PowerShell profile adapter to dot-source from a profile.
def write-powershell-adapter [
  path: path # Destination file.
] {
  save-lines $path [
    "# Generated by Reseed; dot-source this file from the current user's PowerShell profile."
    '$env:PNPM_HOME = Join-Path $HOME ".local\share\reseed\bin"'
    '$env:UV_TOOL_BIN_DIR = $env:PNPM_HOME'
    '$env:YARN_PREFIX = Split-Path $env:PNPM_HOME -Parent'
    '$env:BUN_INSTALL = $env:YARN_PREFIX'
    'if (($env:Path -split [IO.Path]::PathSeparator) -notcontains $env:PNPM_HOME) { $env:Path = "$env:PNPM_HOME$([IO.Path]::PathSeparator)$env:Path" }'
  ]
}

# Write the POSIX profile adapter to source from bash, zsh, or similar.
def write-posix-adapter [
  path: path # Destination file.
] {
  save-lines $path [
    "# Generated by Reseed; source this file from bash, zsh, or another POSIX profile."
    'export PNPM_HOME="$HOME/.local/share/reseed/bin"'
    'export UV_TOOL_BIN_DIR="$PNPM_HOME"'
    'export YARN_PREFIX="$HOME/.local/share/reseed"'
    'export BUN_INSTALL="$YARN_PREFIX"'
    # case guard avoids appending the managed bin twice.
    'case ":$PATH:" in *":$PNPM_HOME:"*) ;; *) export PATH="$PNPM_HOME:$PATH" ;; esac'
  ]
}

# Generate shell integrations for the managed tools: a Nushell Starship
# autoload, a Nushell environment snippet, and Fish/PowerShell/POSIX
# adapters that point the package managers at ~/.local/share/reseed/bin.
def main [] {
  if (which starship | is-empty) {
    error make {msg: "starship is required before shell integration is configured"}
  }

  let home = $nu.home-dir
  let managed_bin = ($home | path join ".local" "share" "reseed" "bin")
  let managed_root = ($managed_bin | path dirname)
  let managed_shell = ($home | path join ".local" "share" "reseed" "shell")
  let managed_bin_literal = ($managed_bin | to nuon)
  let managed_root_literal = ($managed_root | to nuon)

  let nu_autoload_dir = ($nu.data-dir | path join "vendor" "autoload")
  let starship_init = ($nu_autoload_dir | path join "starship.nu")
  let managed_nu = ($nu_autoload_dir | path join "reseed-managed-tools.nu")

  install-starship-nushell $nu_autoload_dir $starship_init
  write-managed-tools-nu $managed_nu $managed_bin_literal $managed_root_literal
  write-fish-adapter ($home | path join ".config" "fish" "conf.d" "reseed-managed-tools.fish")
  write-powershell-adapter ($managed_shell | path join "reseed-managed-tools.ps1")
  write-posix-adapter ($managed_shell | path join "reseed-managed-tools.sh")

  print $"reseed: Nushell Starship autoload: ($starship_init)"
  print $"reseed: managed binary directory: ($managed_bin)"
  print $"reseed: shell adapters: ($managed_shell)"
}
