#!/usr/bin/env nu

const loader_begin = "# >>> Reseed managed tools >>>"
const loader_end = "# <<< Reseed managed tools <<<"

# Save generated content through a sibling temporary file so a failed restore
# cannot leave a partially written shell program.
def save-text [path: path content: string] {
  mkdir ($path | path dirname)
  let temporary = $"($path).(random uuid).tmp"
  $content | save --force $temporary
  mv --force $temporary $path
}

def save-lines [path: path lines: list<string>] {
  save-text $path (($lines | str join "\n") + "\n")
}

# Quote an absolute path for generated shell source.
def quote-shell [value: string syntax: string]: nothing -> string {
  let normalized = if $syntax in [fish posix] { $value | str replace --all "\\" "/" } else { $value }
  match $syntax {
    nu => ($normalized | to nuon)
    fish => {
      let escaped = ($normalized
        | str replace --all "\\" "\\\\"
        | str replace --all '"' '\\"'
        | str replace --all '$' '\\$')
      '"' + $escaped + '"'
    }
    powershell => ("'" + ($normalized | str replace --all "'" "''") + "'")
    _ => ("'" + ($normalized | str replace --all "'" "'\\''") + "'")
  }
}

def run-generated-command [program: string args: list<string> label: string]: nothing -> string {
  let result = (try {
    run-external $program ...$args | complete
  } catch {|error|
    {exit_code: 127 stdout: "" stderr: ($error.msg? | default ($error | to nuon))}
  })
  if $result.exit_code != 0 {
    let detail = if ($result.stderr | str trim | is-empty) { $result.stdout | str trim } else { $result.stderr | str trim }
    error make {msg: $"Failed to generate ($label): ($detail)"}
  }
  $result.stdout
}

def detected-homebrew-prefix []: nothing -> any {
  let declared = ($env.HOMEBREW_PREFIX? | default "" | str trim)
  if not ($declared | is-empty) and ($declared | path exists) {
    return ($declared | path expand --no-symlink)
  }

  let standard = [
    /opt/homebrew/bin/brew
    /usr/local/bin/brew
    /home/linuxbrew/.linuxbrew/bin/brew
    ($nu.home-dir | path join ".linuxbrew" "bin" "brew")
  ] | where {|candidate| $candidate | path exists }
  let programs = if (which brew | is-empty) { $standard } else { [brew] | append $standard }
  for program in $programs {
    let result = (try { run-external $program "--prefix" | complete } catch { {exit_code: 1 stdout: "" stderr: ""} })
    if $result.exit_code == 0 and not (($result.stdout | str trim) | is-empty) {
      return ($result.stdout | str trim | path expand --no-symlink)
    }
  }
  null
}

# Nushell loads these files alphabetically: environment first, then mise's
# hook registration, then Starship. This avoids relying on prompt timing.
def write-nushell-environment [
  path: path
  managed_bin: path
  cargo_bin: path
  mise_config: path
  brew_prefix: any
] {
  mut lines = ["# Generated by Reseed; changes are overwritten by the next restore."]
  let managed_root = ($managed_bin | path dirname)
  $lines = ($lines | append [
    $"$env.PNPM_HOME = (quote-shell ($managed_root | into string) nu)"
    $"$env.UV_TOOL_BIN_DIR = (quote-shell ($managed_bin | into string) nu)"
    $"$env.YARN_PREFIX = (quote-shell ($managed_root | into string) nu)"
    $"$env.BUN_INSTALL = (quote-shell ($managed_root | into string) nu)"
    $"$env.CARGO_INSTALL_ROOT = (quote-shell ($managed_root | into string) nu)"
    $"let reseed_cargo_bin = (quote-shell ($cargo_bin | into string) nu)"
    "if ($reseed_cargo_bin | path exists) { $env.PATH = ($env.PATH | prepend $reseed_cargo_bin | uniq) }"
  ])
  if $brew_prefix != null {
    let brew_sbin = ($brew_prefix | path join "sbin")
    let brew_bin = ($brew_prefix | path join "bin")
    $lines = ($lines | append [
      $"let reseed_brew_sbin = (quote-shell ($brew_sbin | into string) nu)"
      "if ($reseed_brew_sbin | path exists) { $env.PATH = ($env.PATH | prepend $reseed_brew_sbin | uniq) }"
      $"let reseed_brew_bin = (quote-shell ($brew_bin | into string) nu)"
      "if ($reseed_brew_bin | path exists) { $env.PATH = ($env.PATH | prepend $reseed_brew_bin | uniq) }"
    ])
  }
  $lines = ($lines | append [
    "$env.PATH = ($env.PATH | prepend ($env.PNPM_HOME | path join \"bin\") | uniq)"
    $"$env.MISE_GLOBAL_CONFIG_FILE = (quote-shell ($mise_config | into string) nu)"
  ])
  save-lines $path $lines
}

def write-fish-adapter [
  path: path
  managed_bin: path
  cargo_bin: path
  mise_config: path
  brew_prefix: any
] {
  let managed_root = ($managed_bin | path dirname)
  mut lines = [
    "# Generated by Reseed; changes are overwritten by the next restore."
    $"set -gx PNPM_HOME (quote-shell ($managed_root | into string) fish)"
    $"set -gx UV_TOOL_BIN_DIR (quote-shell ($managed_bin | into string) fish)"
    $"set -gx YARN_PREFIX (quote-shell ($managed_root | into string) fish)"
    $"set -gx BUN_INSTALL (quote-shell ($managed_root | into string) fish)"
    $"set -gx CARGO_INSTALL_ROOT (quote-shell ($managed_root | into string) fish)"
    $"if test -d (quote-shell ($cargo_bin | into string) fish)"
    $"    fish_add_path --move --path (quote-shell ($cargo_bin | into string) fish)"
    "end"
  ]
  if $brew_prefix != null {
    for child in [sbin bin] {
      let directory = ($brew_prefix | path join $child)
      $lines = ($lines | append [
        $"if test -d (quote-shell ($directory | into string) fish)"
        $"    fish_add_path --move --path (quote-shell ($directory | into string) fish)"
        "end"
      ])
    }
  }
  $lines = ($lines | append [
    "fish_add_path --move --path $PNPM_HOME/bin"
    $"set -gx MISE_GLOBAL_CONFIG_FILE (quote-shell ($mise_config | into string) fish)"
    "if command -q mise"
    "    mise activate fish | source"
    "else"
    "    echo 'reseed: mise is unavailable; managed tools were not activated' >&2"
    "end"
  ])
  save-lines $path $lines
}

def write-powershell-adapter [
  path: path
  managed_bin: path
  cargo_bin: path
  mise_config: path
  brew_prefix: any
] {
  let managed_root = ($managed_bin | path dirname)
  mut lines = [
    "# Generated by Reseed; changes are overwritten by the next restore."
    $"$env:PNPM_HOME = (quote-shell ($managed_root | into string) powershell)"
    "$env:UV_TOOL_BIN_DIR = (Join-Path $env:PNPM_HOME 'bin')"
    $"$env:YARN_PREFIX = (quote-shell ($managed_root | into string) powershell)"
    "$env:BUN_INSTALL = $env:YARN_PREFIX"
    "$env:CARGO_INSTALL_ROOT = $env:YARN_PREFIX"
    "function Add-ReseedPath([string] $Directory) {"
    "    if ((Test-Path -LiteralPath $Directory) -and (($env:Path -split [IO.Path]::PathSeparator) -notcontains $Directory)) {"
    "        $env:Path = \"$Directory$([IO.Path]::PathSeparator)$env:Path\""
    "    }"
    "}"
    $"Add-ReseedPath (quote-shell ($cargo_bin | into string) powershell)"
  ]
  if $brew_prefix != null {
    for child in [sbin bin] {
      let directory = ($brew_prefix | path join $child)
      $lines = ($lines | append $"Add-ReseedPath (quote-shell ($directory | into string) powershell)")
    }
  }
  $lines = ($lines | append [
    "Add-ReseedPath (Join-Path $env:PNPM_HOME 'bin')"
    "Remove-Item -LiteralPath Function:\\Add-ReseedPath"
    $"$env:MISE_GLOBAL_CONFIG_FILE = (quote-shell ($mise_config | into string) powershell)"
    "if (Get-Command mise -ErrorAction SilentlyContinue) {"
    "    mise activate pwsh | Out-String | Invoke-Expression"
    "} else {"
    "    Write-Warning 'Reseed: mise is unavailable; managed tools were not activated'"
    "}"
  ])
  save-lines $path $lines
}

def posix-adapter-lines [
  shell: string
  managed_bin: path
  cargo_bin: path
  mise_config: path
  brew_prefix: any
]: nothing -> list<string> {
  let managed_root = ($managed_bin | path dirname)
  mut lines = [
    "# Generated by Reseed; changes are overwritten by the next restore."
    $"export PNPM_HOME=(quote-shell ($managed_root | into string) posix)"
    $"export UV_TOOL_BIN_DIR=(quote-shell ($managed_bin | into string) posix)"
    $"export YARN_PREFIX=(quote-shell ($managed_root | into string) posix)"
    "export BUN_INSTALL=$YARN_PREFIX"
    "export CARGO_INSTALL_ROOT=$YARN_PREFIX"
    "reseed_prepend_path() {"
    "  case :$PATH: in *\":$1:\"*) ;; *) PATH=$1:$PATH ;; esac"
    "}"
    $"[ ! -d (quote-shell ($cargo_bin | into string) posix) ] || reseed_prepend_path (quote-shell ($cargo_bin | into string) posix)"
  ]
  if $brew_prefix != null {
    for child in [sbin bin] {
      let directory = ($brew_prefix | path join $child)
      $lines = ($lines | append $"[ ! -d (quote-shell ($directory | into string) posix) ] || reseed_prepend_path (quote-shell ($directory | into string) posix)")
    }
  }
  $lines = ($lines | append [
    "reseed_prepend_path \"$PNPM_HOME/bin\""
    "export PATH"
    $"export MISE_GLOBAL_CONFIG_FILE=(quote-shell ($mise_config | into string) posix)"
    "unset -f reseed_prepend_path 2>/dev/null || true"
  ])
  let activation = match $shell {
    bash => "if command -v mise >/dev/null 2>&1; then eval \"$(mise activate bash)\"; else echo 'reseed: mise is unavailable; managed tools were not activated' >&2; fi"
    zsh => "if command -v mise >/dev/null 2>&1; then eval \"$(mise activate zsh)\"; else echo 'reseed: mise is unavailable; managed tools were not activated' >&2; fi"
    _ => "if command -v mise >/dev/null 2>&1; then if [ -n \"${ZSH_VERSION:-}\" ]; then eval \"$(mise activate zsh)\"; elif [ -n \"${BASH_VERSION:-}\" ]; then eval \"$(mise activate bash)\"; fi; else echo 'reseed: mise is unavailable; managed tools were not activated' >&2; fi"
  }
  $lines | append $activation
}

def chezmoi-manages [state_root: path target: path]: nothing -> bool {
  if (which chezmoi | is-empty) { return false }
  let result = (try {
    ^chezmoi --source ($state_root | into string) source-path ($target | into string) | complete
  } catch {
    {exit_code: 1 stdout: "" stderr: ""}
  })
  ($result.exit_code == 0) and not (($result.stdout | str trim) | is-empty)
}

# Install or refresh the Reseed-owned block in an unmanaged profile. A profile
# owned by chezmoi remains authoritative and must already source the adapter.
def profile-sources-adapter [content: string adapter: path]: nothing -> bool {
  ($content | str contains ($adapter | into string)) or ($content | str contains ($adapter | path basename))
}

def ensure-profile-loader [
  profile: path
  adapter: path
  loader: string
  state_root: path
] {
  let existing = if ($profile | path exists) { open --raw $profile } else { "" }
  if (chezmoi-manages $state_root $profile) {
    if not (profile-sources-adapter $existing $adapter) {
      error make {msg: $"Chezmoi-managed profile must source the generated adapter: ($profile) -> ($adapter)"}
    }
    return
  }

  let pattern = '(?ms)^# >>> Reseed managed tools >>>\r?\n.*?^# <<< Reseed managed tools <<<\r?\n?'
  let stripped = ($existing | str replace --all --regex $pattern "")
  let separator = if ($stripped | is-empty) or ($stripped | str ends-with "\n\n") {
    ""
  } else if ($stripped | str ends-with "\n") {
    "\n"
  } else {
    "\n\n"
  }
  let prefix = $stripped + $separator
  save-text $profile ($prefix + $loader_begin + "\n" + $loader + "\n" + $loader_end + "\n")
}

def detected-powershell-profile [program: string]: nothing -> any {
  let result = (try {
    run-external $program "-NoLogo" "-NoProfile" "-Command" '$PROFILE.CurrentUserCurrentHost' | complete
  } catch {
    {exit_code: 1 stdout: "" stderr: ""}
  })
  let profile = ($result.stdout | str trim)
  if $result.exit_code == 0 and not ($profile | is-empty) {
    $profile | path expand --no-symlink
  } else {
    null
  }
}

def powershell-profile-paths [home: path]: nothing -> list<path> {
  let fallbacks = if $nu.os-info.name == "windows" {
    [
      ($home | path join "Documents" "PowerShell" "Microsoft.PowerShell_profile.ps1")
      ($home | path join "Documents" "WindowsPowerShell" "Microsoft.PowerShell_profile.ps1")
    ]
  } else {
    [($home | path join ".config" "powershell" "Microsoft.PowerShell_profile.ps1")]
  }
  if ($home | path expand --no-symlink) != ($nu.home-dir | path expand --no-symlink) {
    return $fallbacks
  }

  let programs = if $nu.os-info.name == "windows" { [pwsh powershell] } else { [pwsh] }
  let detected = ($programs | each {|program| detected-powershell-profile $program } | compact | uniq)
  if ($detected | is-empty) { $fallbacks } else { $detected }
}

def install-profile-loaders [
  home: path
  state_root: path
  bash_adapter: path
  zsh_adapter: path
  powershell_adapter: path
] {
  ensure-profile-loader ($home | path join ".bashrc") $bash_adapter $". (quote-shell ($bash_adapter | into string) posix)" $state_root
  ensure-profile-loader ($home | path join ".zshrc") $zsh_adapter $". (quote-shell ($zsh_adapter | into string) posix)" $state_root

  for profile in (powershell-profile-paths $home) {
    ensure-profile-loader $profile $powershell_adapter $". (quote-shell ($powershell_adapter | into string) powershell)" $state_root
  }
}

def remove-generated [paths: list<path>] {
  for path in $paths {
    if ($path | path exists) { rm --force $path }
  }
}

def remove-nushell-generated [autoload: path] {
  remove-generated [
    ($autoload | path join "mise.nu")
    ($autoload | path join "reseed-10-environment.nu")
    ($autoload | path join "reseed-20-mise.nu")
    ($autoload | path join "reseed-managed-tools.nu")
    ($autoload | path join "starship.nu")
  ]
}

def main [
  --home: path = $nu.home-dir # Home directory for generated adapters and loaders.
  --data-dir: path = $nu.data-dir # Nushell data directory for autoload files.
  --mise-config: path = "" # Mise config exposed to interactive shells.
  --state-root: path = "" # Chezmoi source used to protect managed profiles.
  --cargo-home: path = "" # Cargo home whose bin directory is the rustup fallback.
  --xdg-config-home: path = "" # XDG config root containing Fish configuration.
  --skip-profile-loaders # Generate adapters without changing shell profiles.
  --starship-init-source: path = "" # Pre-generated Starship source for isolated/offline generation.
  --mise-activation-source: path = "" # Pre-generated mise source for isolated/offline generation.
] {
  let use_starship_source = not (($starship_init_source | into string | str trim) | is-empty)
  let use_mise_source = not (($mise_activation_source | into string | str trim) | is-empty)
  let nu_autoload_dir = ($data_dir | path join "vendor" "autoload")
  if not $use_starship_source and (which starship | is-empty) {
    remove-nushell-generated $nu_autoload_dir
    error make {msg: "starship is required before shell integration is configured"}
  }
  if not $use_mise_source and (which mise | is-empty) {
    remove-nushell-generated $nu_autoload_dir
    error make {msg: "mise is required before shell integration is configured"}
  }

  let configured_mise = if not (($mise_config | into string | str trim) | is-empty) {
    $mise_config
  } else if not (($env.RESEED_MISE_CONFIG_FILE? | default "" | str trim) | is-empty) {
    $env.RESEED_MISE_CONFIG_FILE
  } else {
    $env.FILE_PWD | path dirname | path join "mise.toml"
  }
  let configured_root = if not (($state_root | into string | str trim) | is-empty) {
    $state_root
  } else if not (($env.RESEED_STATE_ROOT? | default "" | str trim) | is-empty) {
    $env.RESEED_STATE_ROOT
  } else {
    $configured_mise | path dirname
  }
  let mise_config_path = ($configured_mise | path expand --no-symlink)
  let state_root_path = ($configured_root | path expand --no-symlink)
  if not ($mise_config_path | path exists) {
    error make {msg: $"Selected mise shell config does not exist: ($mise_config_path)"}
  }

  let configured_cargo_home = if not (($cargo_home | into string | str trim) | is-empty) {
    $cargo_home
  } else if not (($env.CARGO_HOME? | default "" | str trim) | is-empty) {
    $env.CARGO_HOME
  } else {
    $home | path join ".cargo"
  }
  let configured_xdg_home = if not (($xdg_config_home | into string | str trim) | is-empty) {
    $xdg_config_home
  } else if not (($env.XDG_CONFIG_HOME? | default "" | str trim) | is-empty) {
    $env.XDG_CONFIG_HOME
  } else {
    $home | path join ".config"
  }

  let managed_root = ($home | path join ".local" "share" "reseed")
  let managed_bin = ($managed_root | path join "bin")
  let cargo_bin = ($configured_cargo_home | path expand --no-symlink | path join "bin")
  let fish_config_home = ($configured_xdg_home | path expand --no-symlink)
  let managed_shell = ($managed_root | path join "shell")
  let brew_prefix = (detected-homebrew-prefix)
  let starship_init = ($nu_autoload_dir | path join "starship.nu")
  let nu_environment = ($nu_autoload_dir | path join "reseed-10-environment.nu")
  let nu_mise = ($nu_autoload_dir | path join "reseed-20-mise.nu")
  let fish_adapter = ($fish_config_home | path join "fish" "conf.d" "reseed-managed-tools.fish")
  let powershell_adapter = ($managed_shell | path join "reseed-managed-tools.ps1")
  let bash_adapter = ($managed_shell | path join "reseed-managed-tools.bash")
  let zsh_adapter = ($managed_shell | path join "reseed-managed-tools.zsh")
  let posix_adapter = ($managed_shell | path join "reseed-managed-tools.sh")

  mkdir $managed_bin
  let starship_source = if $use_starship_source {
    if not ($starship_init_source | path exists) { error make {msg: $"Starship init source does not exist: ($starship_init_source)"} }
    open --raw $starship_init_source
  } else {
    run-generated-command starship [init nu] "Nushell Starship activation"
  }
  let mise_source = (try {
    if $use_mise_source {
      if not ($mise_activation_source | path exists) { error make {msg: $"Mise activation source does not exist: ($mise_activation_source)"} }
      open --raw $mise_activation_source
    } else {
      run-generated-command mise [activate nu] "Nushell mise activation"
    }
  } catch {|error|
    remove-nushell-generated $nu_autoload_dir
    error make {msg: ($error.msg? | default ($error | to nuon))}
  })
  save-text $starship_init $starship_source
  write-nushell-environment $nu_environment $managed_bin $cargo_bin $mise_config_path $brew_prefix
  save-text $nu_mise $mise_source
  write-fish-adapter $fish_adapter $managed_bin $cargo_bin $mise_config_path $brew_prefix
  write-powershell-adapter $powershell_adapter $managed_bin $cargo_bin $mise_config_path $brew_prefix
  save-lines $bash_adapter (posix-adapter-lines bash $managed_bin $cargo_bin $mise_config_path $brew_prefix)
  save-lines $zsh_adapter (posix-adapter-lines zsh $managed_bin $cargo_bin $mise_config_path $brew_prefix)
  save-lines $posix_adapter (posix-adapter-lines dispatch $managed_bin $cargo_bin $mise_config_path $brew_prefix)

  remove-generated [
    ($nu_autoload_dir | path join "mise.nu")
    ($nu_autoload_dir | path join "reseed-managed-tools.nu")
  ]
  if not $skip_profile_loaders {
    install-profile-loaders $home $state_root_path $bash_adapter $zsh_adapter $powershell_adapter
  }

  print $"reseed: selected mise shell config: ($mise_config_path)"
  print $"reseed: Nushell autoload directory: ($nu_autoload_dir)"
  print $"reseed: managed binary directory: ($managed_bin)"
  print $"reseed: shell adapters: ($managed_shell)"
}
